[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

optimizer = true
optimizer_runs = 1_000_000
solc_version = '0.8.21'

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
fail_on_revert = false
# runs = 1
# depth = 100_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config