[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

optimizer = true
optimizer_runs = 1_000_000
evm_version = "paris"
solc_version = '0.8.21'
line_length = 100                                         # While we allow up to 120, we lint at 100 for readability.
fs_permissions = [{ access = "read-write", path = "./" }]
ignored_warnings_from = ["node_modules", "lib","test"]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
# fail_on_revert = false
# depth = 10
runs = 10
# depth = 100_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.report.fuzz]
runs = 1

[profile.report.invariant]
depth = 1
runs = 1
